"""Add product_id to Coupon

Revision ID: 0f496b67e39a
Revises: 20260228_add_category_fields
Create Date: 2026-03-01 23:35:07.631129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f496b67e39a'
down_revision: Union[str, Sequence[str], None] = '20260228_add_category_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'coupons', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coupons', type_='foreignkey')
    op.drop_column('coupons', 'product_id')
    # ### end Alembic commands ###
