"""Add due_date to Expense model

Revision ID: 2d3abc92f615
Revises: 3934eb25fa71
Create Date: 2026-03-02 18:58:55.428326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d3abc92f615'
down_revision: Union[str, Sequence[str], None] = '3934eb25fa71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('due_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'due_date')
    # ### end Alembic commands ###