"""dish_template_table

Revision ID: 2fc63ff26c79
Revises: b4975c2782d1
Create Date: 2026-01-02 10:58:37.774427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fc63ff26c79'
down_revision: Union[str, Sequence[str], None] = 'b4975c2782d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Safely drop index if exists
    op.execute("""
    DO $$
    BEGIN
        IF EXISTS (
            SELECT 1 FROM pg_indexes
            WHERE indexname = 'ix_coupon_categories_id'
        ) THEN
            DROP INDEX ix_coupon_categories_id;
        END IF;
    END$$;
    """)

    # Safely drop tables if they exist
    op.execute("DROP TABLE IF EXISTS coupon_categories CASCADE;")
    op.execute("DROP TABLE IF EXISTS order_coupons CASCADE;")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_coupons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('coupon_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name=op.f('order_coupons_coupon_id_fkey')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('order_coupons_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_coupons_pkey'))
    )
    op.create_index(op.f('ix_order_coupons_id'), 'order_coupons', ['id'], unique=False)
    op.create_table('coupon_categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('coupon_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('coupon_categories_category_id_fkey')),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name=op.f('coupon_categories_coupon_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('coupon_categories_pkey'))
    )
    op.create_index(op.f('ix_coupon_categories_id'), 'coupon_categories', ['id'], unique=False)
    # ### end Alembic commands ###
