"""add printer fields to category

Revision ID: 42177f6c3fb4
Revises: 2d3abc92f615
Create Date: 2026-03-06 06:06:44.768678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42177f6c3fb4'
down_revision: Union[str, Sequence[str], None] = '2d3abc92f615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('printer_ip', sa.String(length=50), nullable=True))
    op.add_column('categories', sa.Column('printer_port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'printer_port')
    op.drop_column('categories', 'printer_ip')
    # ### end Alembic commands ###
