"""Added Payment field to orders

Revision ID: b7475fa068d6
Revises: 2fc63ff26c79
Create Date: 2026-01-10 16:40:13.119311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7475fa068d6'
down_revision: Union[str, Sequence[str], None] = '2fc63ff26c79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
    DO $$
    BEGIN
        IF EXISTS (
            SELECT 1 FROM information_schema.tables
            WHERE table_name = 'orders'
        ) THEN
            ALTER TABLE orders
            ADD COLUMN IF NOT EXISTS payment_method VARCHAR(50);
        END IF;
    END$$;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_method')
    op.create_table('coupon_categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('coupon_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('coupon_categories_category_id_fkey')),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name=op.f('coupon_categories_coupon_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('coupon_categories_pkey'))
    )
    op.create_index(op.f('ix_coupon_categories_id'), 'coupon_categories', ['id'], unique=False)
    op.create_table('order_coupons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('coupon_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name=op.f('order_coupons_coupon_id_fkey')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('order_coupons_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_coupons_pkey'))
    )
    op.create_index(op.f('ix_order_coupons_id'), 'order_coupons', ['id'], unique=False)
    # ### end Alembic commands ###
