"""Implement status field and clean up PrintJob

Revision ID: f9995b29f786
Revises: 42177f6c3fb4
Create Date: 2026-03-08 11:02:48.225957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9995b29f786'
down_revision: Union[str, Sequence[str], None] = '42177f6c3fb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('print_jobs', sa.Column('status', sa.String(length=20), nullable=False))
    op.drop_column('print_jobs', 'is_printed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('print_jobs', sa.Column('is_printed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('print_jobs', 'status')
    # ### end Alembic commands ###
